[versions]
java = "21"
kotlin = "1.9.23"
springBoot = "3.4.2"
dependencyManagement = "1.1.4"
detekt = "1.23.5"
ksp = "1.9.23-1.0.19" # KSP версия должна строго соответствовать версии Kotlin

[libraries]
# Spring
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }

# Testing
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
dependency-management = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
